import type { Metadata } from "next";
import localFont from "next/font/local";

import { FontProvider } from "@/context/font-context";
import { ThemeProvider } from "@/context/theme-context";

import "./globals.css";

const montserrat = localFont({
  src: "../public/fonts/Montserrat/Montserrat-VariableFont_wght.ttf",
  display: "swap",
  variable: "--font-montserrat",
});

const inter = localFont({
  src: "../public/fonts/Inter/Inter-VariableFont.ttf",
  display: "swap",
  preload: true,
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${inter.variable} antialiased`}>
        <ThemeProvider>
          <FontProvider>{children}</FontProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
