import ActivityFilter from "@/features/activity/components/activity-filter";
import ActivityItem from "@/features/activity/components/activity-item";
import { ActivityLog } from "@/types/api";

const data: ActivityLog[] = [
  {
    id: "1",
    category: "inventory",
    action: "created",
    severity: "info",
    title: "Inventory item created",
    description: "Wireless Mouse (WM-2024-001) added to catalog",
    entityType: "inventory_item",
    entityId: "item_001",
    entityName: "Wireless Mouse",
    performedBy: "user_001",
    createdAt: new Date("2023-01-15T08:30:00Z"),
    updatedAt: new Date("2024-10-28T14:20:00Z"),
  },
  {
    id: "2",
    category: "inventory",
    action: "updated",
    severity: "info",
    title: "Inventory item updated",
    description: "Updated Wireless Mouse details",
    entityType: "inventory_item",
    entityId: "item_001",
    entityName: "Wireless Mouse",
    performedBy: "user_001",
    changes: [
      { field: "unitCost", oldValue: 19.99, newValue: 24.99 },
      { field: "description", oldValue: "Old desc", newValue: "New desc" },
    ],
    createdAt: new Date("2023-01-15T08:30:00Z"),
    updatedAt: new Date("2024-10-28T14:20:00Z"),
  },
  {
    id: "3",
    category: "inventory",
    action: "deleted",
    severity: "warning",
    title: "Inventory item deleted",
    description: "USB Hub (HD-USB-4PORT) permanently deleted",
    entityType: "inventory_item",
    entityId: "item_005",
    entityName: "USB Hub",
    performedBy: "user_001",
    createdAt: new Date("2023-01-15T08:30:00Z"),
    updatedAt: new Date("2024-10-28T14:20:00Z"),
  },
  {
    id: "4",
    category: "inventory",
    action: "deactivated",
    severity: "info",
    title: "Inventory item deactivated",
    description: "Old Printer marked as inactive",
    entityType: "inventory_item",
    entityId: "item_030",
    performedBy: "user_001",
    entityName: "Old Printer",
    createdAt: new Date("2023-01-15T08:30:00Z"),
    updatedAt: new Date("2024-10-28T14:20:00Z"),
  },
  {
    id: "5",
    category: "stock",
    action: "adjusted",
    severity: "info",
    title: "Stock adjusted",
    description: "Wireless Mouse stock adjusted at WH-NYC (+50 units)",
    entityType: "stock_adjustment",
    entityId: "adj_001",
    metadata: {
      inventoryItemId: "item_001",
      inventoryItemName: "Wireless Mouse",
      locationId: "loc_001",
      locationName: "WH-NYC",
      quantityChange: 50,
      reason: "received_from_supplier",
      previousQuantity: 400,
      newQuantity: 450,
    },
    locationId: "loc_001",
    performedBy: "user_001",
    createdAt: new Date("2023-01-15T08:30:00Z"),
    updatedAt: new Date("2024-10-28T14:20:00Z"),
  },
  {
    id: "6",
    category: "stock",
    action: "transferred",
    severity: "info",
    title: "Stock transfer initiated",
    description: "150 units reserved for shipment SHP-2024-001",
    entityType: "shipment",
    entityId: "ship_001",
    entityName: "SHP-2024-001",
    metadata: {
      fromLocation: "WH-NYC",
      toLocation: "DC-LA",
      itemCount: 2,
      totalUnits: 150,
    },
    performedBy: "user_001",
    createdAt: new Date("2023-01-15T08:30:00Z"),
    updatedAt: new Date("2024-10-28T14:20:00Z"),
  },
  {
    id: "7",
    category: "stock",
    action: "restocked",
    severity: "info",
    title: "Stock restocked",
    description: "150 units received at DC-LA from shipment SHP-2024-001",
    entityType: "shipment",
    entityId: "ship_001",
    entityName: "SHP-2024-001",
    metadata: {
      fromLocation: "WH-NYC",
      toLocation: "DC-LA",
      itemCount: 2,
      totalUnits: 150,
    },
    locationId: "loc_002",
    performedBy: "user_001",
    createdAt: new Date("2023-01-15T08:30:00Z"),
    updatedAt: new Date("2024-10-28T14:20:00Z"),
  },
  {
    id: "8",
    category: "stock",
    action: "updated",
    severity: "warning",
    title: "Low stock alert",
    description: "Wireless Mouse at STORE-PDX below reorder point (12 < 15)",
    entityType: "stock_level",
    entityId: "stock_008",
    metadata: {
      inventoryItemId: "item_001",
      inventoryItemName: "Wireless Mouse",
      locationId: "loc_009",
      locationName: "STORE-PDX",
      currentQuantity: 12,
      reorderPoint: 15,
    },
    locationId: "loc_009",
    performedBy: "user_001",
    createdAt: new Date("2023-01-15T08:30:00Z"),
    updatedAt: new Date("2024-10-28T14:20:00Z"),
  },
  {
    id: "9",
    category: "location",
    action: "created",
    severity: "info",
    title: "Location created",
    description: "New warehouse added: Central Warehouse NYC (WH-NYC)",
    entityType: "location",
    entityId: "loc_001",
    entityName: "Central Warehouse NYC",
    performedBy: "user_001",
    createdAt: new Date("2023-01-15T08:30:00Z"),
    updatedAt: new Date("2024-10-28T14:20:00Z"),
  },
  {
    id: "10",
    category: "location",
    action: "updated",
    severity: "info",
    title: "Location updated",
    description: "Updated Miami Retail Store details",
    entityType: "location",
    entityId: "loc_004",
    entityName: "Miami Retail Store",
    changes: [
      { field: "managerName", oldValue: "Old Manager", newValue: "Isabella Rodriguez" },
      { field: "phone", oldValue: "+1 (305) 555-0000", newValue: "+1 (305) 555-0234" },
    ],
    performedBy: "user_001",
    createdAt: new Date("2023-01-15T08:30:00Z"),
    updatedAt: new Date("2024-10-28T14:20:00Z"),
  },
  {
    id: "11",
    category: "location",
    action: "deactivated",
    severity: "warning",
    title: "Location deactivated",
    description: "Philadelphia Warehouse - OLD marked as inactive",
    entityType: "location",
    entityId: "loc_014",
    entityName: "Philadelphia Warehouse - OLD",
    metadata: {
      reason: "Facility closed, operations moved to new location",
    },
    performedBy: "user_001",
    createdAt: new Date("2023-01-15T08:30:00Z"),
    updatedAt: new Date("2024-10-28T14:20:00Z"),
  },
  {
    id: "12",
    category: "location",
    action: "deleted",
    severity: "critical",
    title: "Location deleted",
    description: "Detroit Warehouse permanently deleted",
    entityType: "location",
    entityId: "loc_018",
    entityName: "Detroit Warehouse",
    metadata: {
      hadStock: false,
      hadActiveShipments: false,
    },
    performedBy: "user_001",
    createdAt: new Date("2023-01-15T08:30:00Z"),
    updatedAt: new Date("2024-10-28T14:20:00Z"),
  },
];

export default function Activity() {
  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-3xl font-bold">Activity Log</h2>
        <p className="text-muted-foreground">Track all system activities, changes, and events</p>
      </div>
      <div className="space-y-6">
        <h2 className="text-2xl">Filters</h2>
        <ActivityFilter />
        <div className="overflow-auto space-y-6">
          {data.map((item) => (
            <ActivityItem key={item.id} {...item} />
          ))}
        </div>
      </div>
    </div>
  );
}
